---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels: 
    dept: engineering
---
apiVersion: v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: myns
  labels:
    dept: engineering
    app: fortune
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        dept: engineering
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 3000
