version: '3'
volumes: 
  data: 
networks:
  nw-net:
services:
  nwdb: 
    image: lifeboey/nwdb:v3
    build:
      context: ./database
    volumes:
    - data:/var/lib/mysql
    networks:
    - nw-net
  nwapp: 
    image: lifeboey/nwapp:v1
    build:
      context: ./server
    environment:
    - DB_HOST=nwdb
    ports: 
    - 8088:3000
    networks:
    - nw-net